single image for boot splash, fixed dockerfile, export templetes weren't in right spot

diff --git a/dcu/config-files/export-all b/dcu/config-files/export-all
--- a/dcu/config-files/export-all
+++ b/dcu/config-files/export-all
@@ -3,20 +3,29 @@
 # first arg is --help or -h             or # of args != 3
 if [[ $1 == --help ]] || [[ $1 == -h ]] || [[ $# -ne 3 ]]; then
     echo "Usage:" $0 "<godot_executable> <path_to_root_folder> <out_path>" 
-    exit
+    exit 1
 fi
 
 # backend
 # cargo build the backend cause yeah
 cd $2/onboard/backend
 cargo build --release
+backend_exit_code=$?
+if [[ $backend_exit_code -ne 0 ]]; then
+    echo "backend failed to compile"
+    exit 2
+fi
 cd $2
 cp $2/onboard/backend/target/release/backend $3/devcade_backend
 
 # godot frontend
 /usr/bin/dotnet build "$2/onboard/godot-frontend/godot-frontend.csproj" -c Release
-echo -e "build solutions return code $?"
-$1 --path $2/onboard/godot-frontend --headless --export-release "Linux" $3/devcade_frontend
-echo -e "compile return code: $?"
 
-exit
+$1 --path $2/onboard/godot-frontend --headless --export-release "Linux" $3/devcade_frontend
+frontend_exit_code=$?
+if [[ $frontend_exit_code -ne 0 ]]; then
+    echo "frontend failed to compile"
+    exit 3
+fi
+
+exit 0
